'''
Project Euler Challenge 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

n1 = 1
n2 = 2
fibs = [1, 2]
looping = True

while looping:
    fib_sum = n1 + n2
    if fib_sum < 4000000:
        fibs.append(fib_sum)
        # Set the next Fibonacci iteration
        n1 = n2
        n2 = fib_sum
    else:
        # Break the loop if over the set value
        looping = False
        break

print("All Fibonacci: %s" % fibs)

sum_evens = 0
for n in fibs:
    if n % 2 == 0:
        sum_evens += n

print("Sum of even Fibonacci: %s" % sum_evens)
